timeout: 3000s
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'build'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud config set dataproc/region us-central1
      ./createImage.sh boot.sh